### ISSUE TITLE
statusCode: 401 Unable to verify authorization token when talking to apple

### ISSUE THREAD

**Issue by liqiongbusc** [marinosoftware/DeviceCheckSample#1]
The printout of the server is :
Updating two bits to:
bit0: false
bit1: true
{ date: 'Mon, 30 Oct 2017 20:51:39 GMT',
  'x-apple-request-uuid': 'eea58795-3b9e-1bca-ab77-5faca16719cd',
  'x-apple-jingle-correlation-key': '52SYPFJ3TYN4VK3XL6WKCZYZZU',
  'apple-seq': '0',
  'apple-tk': 'false',
  'x-responding-instance': '20107',
  'content-type': 'text/plain; charset=UTF-8',
  'content-length': '36' }
statusCode: 401
Unable to verify authorization token

The Key, Teamid, and cert is good. will that be the JWT is not signed correctly?
Thanks!
@mbehan @timcolla

**Comment by liqiongbusc** [comment]
I am using localhost node js server, will that be the issue?

**Comment by timcolla** [comment]
Hi @liqiongbusc,
Sorry for the late reply.

It's not a problem that you're working from localhost, that's what I'm doing as well.
Could you give me a list of your setup? What iOS device, iOS version, node version, anything you can think of basically. 
And what your steps are to recreate this.

Hope this problem has gone away since, but if not let me know.
Cheers,
Tim

**Comment by adnanmitf09** [comment]
statusCode: 401
Unable to verify authorization token
